<?php

use Snowdog\Academy\Controller\Account;

/** @var $this Account */

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <br/>
    <div>
        <form class="form-horizontal" method="post" action="/account/addFundsPost">
            <div class="form-group">
                <label for="input-login" class="col-sm-2 control-label">Amount:</label>
                <div class="col-sm-10">
                    <input type="number" name="amount" class="form-control" id="input-amount" >
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Add Funds</button>
                </div>
            </div>
        </form>
    </div>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
